services:
  backend:
    image: desafio-backend
    pull_policy: never
    container_name: desafio-backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000